import Head from 'next/head'
import Header from './components/Header'
import TeamSection from './components/TeamSection'
import Mint from './components/Mint'
import ContactSection from './components/ContactSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NFT minting Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TeamSection />
      <Mint />
      <ContactSection />
    </div>
  )
}